# Generated by Django 5.1.5 on 2025-02-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Education", models.CharField(max_length=255)),
                ("JoiningYear", models.IntegerField(default=0)),
                ("city", models.CharField(max_length=255)),
                ("Age", models.IntegerField(default=0)),
                ("Gender", models.CharField(max_length=255)),
            ],
        ),
    ]
