# Generated by Django 5.1.5 on 2025-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="Education",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="business",
            old_name="Gender",
            new_name="employees",
        ),
        migrations.RenameField(
            model_name="business",
            old_name="city",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="business",
            name="Age",
        ),
        migrations.RemoveField(
            model_name="business",
            name="JoiningYear",
        ),
        migrations.AddField(
            model_name="business",
            name="profit",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="business",
            name="revenue",
            field=models.FloatField(default=0.0),
        ),
    ]
