# Generated by Django 5.1.5 on 2025-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statapp", "0002_rename_education_business_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="employees",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="business",
            name="profit",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="business",
            name="revenue",
            field=models.IntegerField(default=0),
        ),
    ]
