# Generated by Django 5.1.5 on 2025-02-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statapp", "0003_alter_business_employees_alter_business_profit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="employees",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="business",
            name="profit",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="business",
            name="revenue",
            field=models.FloatField(),
        ),
    ]
