# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myDjangoapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://vj7005.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6fd160b132ac4f09b6d0cab3fa70d476 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a5e5bdb75dd04526b7cc299700b6c3da }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vj7005.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fd160b132ac4f09b6d0cab3fa70d476 }}/statapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myDjangoapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b877ef63fa054b3c835442d19c9abe96 }}
        images: 'vj7005.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fd160b132ac4f09b6d0cab3fa70d476 }}/statapp:${{ github.sha }}'